{{- if .Values.enabledCollectors }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "state-metrics.fullname" . }}
  labels:
    {{- include "state-metrics.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "state-metrics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "state-metrics.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "state-metrics.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if has "lvm" .Values.enabledCollectors }}
          securityContext:
            privileged: true
          {{- else }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: {{ include "state-metrics.image" . }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - -c
            - /config/config.yaml
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
            {{- if .Values.config.debugServer.enabled }}
            - name: debug
              containerPort: 8080
              protocol: TCP
            {{- end }}
            {{- if .Values.config.pprof.enabled }}
            - name: pprof
              containerPort: {{ .Values.config.pprof.port }}
              protocol: TCP
              hostPort: {{ .Values.config.pprof.port }}
            {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: LEADER_ELECTION_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LEADER_ELECTION_LEASE_NAME
              value: {{ include "state-metrics.fullname" . }}
            {{- if .Values.tls.enabled }}
            - name: SERVER_TLS_ENABLED
              value: "true"
            - name: SERVER_TLS_CERT_FILE
              value: "/etc/tls/tls.crt"
            - name: SERVER_TLS_KEY_FILE
              value: "/etc/tls/tls.key"
            {{- end }}
            {{- if .Values.auth.enabled }}
            - name: SERVER_AUTH_ENABLED
              value: "true"
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            {{- if .Values.tls.enabled }}
            - name: tls
              mountPath: /etc/tls
              readOnly: true
            {{- end }}
            {{- if has "lvm" .Values.enabledCollectors }}
            - name: dev
              mountPath: /dev
            - name: lvm-config
              mountPath: /etc/lvm
            - name: kubelet
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              {{- if .Values.config.debugServer.enabled }}
              port: debug
              {{- else }}
              port: {{ .Values.livenessProbe.httpGet.port }}
              {{- if .Values.tls.enabled }}
              scheme: HTTPS
              {{- end }}
              {{- end }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              {{- if .Values.config.debugServer.enabled }}
              port: debug
              {{- else }}
              port: {{ .Values.readinessProbe.httpGet.port }}
              {{- if .Values.tls.enabled }}
              scheme: HTTPS
              {{- end }}
              {{- end }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "state-metrics.fullname" . }}
        {{- if .Values.tls.enabled }}
        - name: tls
          secret:
            secretName: {{ include "state-metrics.fullname" . }}-tls
            defaultMode: 0400
        {{- end }}
        {{- if has "lvm" .Values.enabledCollectors }}
        - name: dev
          hostPath:
            path: /dev
        - name: lvm-config
          hostPath:
            path: /etc/lvm
        - name: kubelet
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
