{{- if .Values.daemonsetConfig.enabledCollectors }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "state-metrics.fullname" . }}-daemonset
  labels:
    {{- include "state-metrics.labels" . | nindent 4 }}
    app.kubernetes.io/component: daemonset
spec:
  selector:
    matchLabels:
      {{- include "state-metrics.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: daemonset
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-daemonset.yaml") . | sha256sum }}
        {{- with .Values.daemonsetConfig.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "state-metrics.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: daemonset
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "state-metrics.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.daemonsetConfig.podSecurityContext | nindent 8 }}
      {{- with .Values.daemonsetConfig.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if has "lvm" .Values.daemonsetConfig.enabledCollectors }}
          securityContext:
            privileged: true
          {{- else }}
          securityContext:
            {{- toYaml .Values.daemonsetConfig.securityContext | nindent 12 }}
          {{- end }}
          image: {{ include "state-metrics.image" . }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - -c
            - /config/config.yaml
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: LEADER_ELECTION_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            {{- if has "lvm" .Values.daemonsetConfig.enabledCollectors }}
            - name: dev
              mountPath: /dev
            - name: lvm-config
              mountPath: /etc/lvm
            - name: kubelet
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.daemonsetConfig.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.daemonsetConfig.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.daemonsetConfig.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "state-metrics.fullname" . }}-daemonset
        {{- if has "lvm" .Values.daemonsetConfig.enabledCollectors }}
        - name: dev
          hostPath:
            path: /dev
        - name: lvm-config
          hostPath:
            path: /etc/lvm
        - name: kubelet
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        {{- end }}
      {{- with .Values.daemonsetConfig.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.daemonsetConfig.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.daemonsetConfig.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
