{{- if .Values.deploymentConfig.enabledCollectors }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "state-metrics.fullname" . }}-deployment
  labels:
    {{- include "state-metrics.labels" . | nindent 4 }}
    app.kubernetes.io/component: deployment
spec:
  replicas: {{ .Values.deploymentConfig.replicaCount }}
  selector:
    matchLabels:
      {{- include "state-metrics.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: deployment
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-deployment.yaml") . | sha256sum }}
        {{- with .Values.deploymentConfig.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "state-metrics.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: deployment
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "state-metrics.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deploymentConfig.podSecurityContext | nindent 8 }}
      {{- with .Values.deploymentConfig.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deploymentConfig.securityContext | nindent 12 }}
          image: {{ include "state-metrics.image" . }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - -c
            - /config/config.yaml
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: LEADER_ELECTION_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          livenessProbe:
            {{- toYaml .Values.deploymentConfig.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.deploymentConfig.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.deploymentConfig.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "state-metrics.fullname" . }}-deployment
      {{- with .Values.deploymentConfig.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deploymentConfig.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deploymentConfig.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
